version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ubuntu
    container_name: Actividad1
    ports:
      - "4000:80"
    volumes:
      - .:/server